CREATE TABLE storage (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name                   varchar(255) UNIQUE NOT NULL,
  description            text
);
CREATE INDEX storage__name__idx ON storage USING HASH(name);

CREATE TABLE item (
  id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  storage_id             bigint NOT NULL REFERENCES storage,
  name                   varchar(255) NOT NULL,
  description            text,
  quantity               int NOT NULL,
  deadline               timestamptz NOT NULL
);
CREATE INDEX item__name__idx ON item USING HASH(name);
CREATE INDEX item__storage_id__idx ON item(storage_id);
CREATE INDEX item__deadline__idx ON item(deadline);
